### ISSUE TITLE
Not able to run the chat extension on Heroku

### ISSUE THREAD

**Issue by jackysatpal** [fbsamples/messenger-bot-samples#13]
I was testing the chat-extensions feature but on Heroku I was not able to run it. 
It is saying "Internal Server Error"

here are the log details:
0mGET / [31m500 [0m0.743 ms - 148[0m
2017-05-24T22:03:06.236808+00:00 app[web.1]: ReferenceError: /app/views/index.ejs:22
2017-05-24T22:03:06.236810+00:00 app[web.1]:     20|             window.attachApp(
2017-05-24T22:03:06.236811+00:00 app[web.1]:     21|               context.psid,
2017-05-24T22:03:06.236811+00:00 app[web.1]:  >> 22|               <%= listId %>,
2017-05-24T22:03:06.236812+00:00 app[web.1]:     23|               "<%= socketAddress %>",
2017-05-24T22:03:06.236812+00:00 app[web.1]:     24|               context.thread_type);
2017-05-24T22:03:06.236813+00:00 app[web.1]:     25|           }, function error(err) {
2017-05-24T22:03:06.263336+00:00 heroku[router]: at=info method=GET path="/" host=cryptic-cliffs-96893.herokuapp.com request_id=c4286f42-7c3b-4eed-ae7b-cf20f215fcc9 fwd="158.106.198.94" dyno=web.1 connect=0ms service=2ms status=500 bytes=404 protocol=https
2017-05-24T22:03:06.236814+00:00 app[web.1]: 
2017-05-24T22:03:06.236815+00:00 app[web.1]: listId is not defined
2017-05-24T22:03:06.236819+00:00 app[web.1]:     at eval (eval at compile (/app/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:22:26)
2017-05-24T22:03:06.236820+00:00 app[web.1]:     at returnedFn (/app/node_modules/ejs/lib/ejs.js:555:17)
2017-05-24T22:03:06.236820+00:00 app[web.1]:     at tryHandleCache (/app/node_modules/ejs/lib/ejs.js:203:34)
2017-05-24T22:03:06.236821+00:00 app[web.1]:     at View.exports.renderFile [as engine] (/app/node_modules/ejs/lib/ejs.js:412:10)
2017-05-24T22:03:06.236822+00:00 app[web.1]:     at View.render (/app/node_modules/express/lib/view.js:128:8)
2017-05-24T22:03:06.236823+00:00 app[web.1]:     at tryRender (/app/node_modules/express/lib/application.js:640:10)
2017-05-24T22:03:06.236823+00:00 app[web.1]:     at Function.render (/app/node_modules/express/lib/application.js:592:3)
2017-05-24T22:03:06.236824+00:00 app[web.1]:     at ServerResponse.render (/app/node_modules/express/lib/response.js:966:7)
2017-05-24T22:03:06.236825+00:00 app[web.1]:     at /app/routes/index.js:15:7
2017-05-24T22:03:06.236826+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-05-24T22:03:06.236826+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-05-24T22:03:06.236827+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-05-24T22:03:06.236828+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-05-24T22:03:06.236828+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2017-05-24T22:03:06.236829+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-05-24T22:03:06.236830+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-05-24T22:03:06.315622+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=cryptic-cliffs-96893.herokuapp.com request_id=36a3cdf3-a652-4108-a73e-0549229c8d04 fwd="158.106.198.94" dyno=web.1 connect=0ms service=2ms status=200 bytes=32270 protocol=https

Anyone faced the same issue?

**Comment by LAMike310** [comment]
How did you fix your issue?
