### ISSUE TITLE
listId is not defined

### ISSUE THREAD

**Issue by eoinclancy1** [fbsamples/messenger-bot-samples#25]
Any ideas how I can resolve this error? The app won't run in Heroku at the minute but I can't find a solution to the problem

`2017-10-17T20:22:52.189838+00:00 app[web.1]:     at returnedFn (/app/node_modules/ejs/lib/ejs.js:555:17)
2017-10-17T20:22:52.189838+00:00 app[web.1]:     at tryHandleCache (/app/node_modules/ejs/lib/ejs.js:203:34)
2017-10-17T20:22:52.189839+00:00 app[web.1]:     at View.exports.renderFile [as engine] (/app/node_modules/ejs/lib/ejs.js:412:10)
2017-10-17T20:22:52.189840+00:00 app[web.1]:     at View.render (/app/node_modules/express/lib/view.js:128:8)
2017-10-17T20:22:52.189841+00:00 app[web.1]:     at tryRender (/app/node_modules/express/lib/application.js:640:10)
2017-10-17T20:22:52.189842+00:00 app[web.1]:     at Function.render (/app/node_modules/express/lib/application.js:592:3)
2017-10-17T20:22:52.189842+00:00 app[web.1]:     at ServerResponse.render (/app/node_modules/express/lib/response.js:966:7)
2017-10-17T20:22:52.189843+00:00 app[web.1]:     at /app/routes/index.js:15:7
2017-10-17T20:22:52.189844+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-10-17T20:22:52.189845+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-10-17T20:22:52.189845+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-10-17T20:22:52.189846+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-10-17T20:22:52.189847+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2017-10-17T20:22:52.189847+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2017-10-17T20:22:52.189848+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:275:10)
2017-10-17T20:28:02.186270+00:00 heroku[router]: at=info method=GET path="/" host=serene-bayou-29655.herokuapp.com request_id=f3391ffa-ca7f-4789-ad56-aa2d7aceace7 fwd="78.19.206.245" dyno=web.1 connect=1ms service=5ms status=500 bytes=404 protocol=https
2017-10-17T20:28:02.184081+00:00 app[web.1]: GET / 500 0.484 ms - 148
2017-10-17T20:28:02.190127+00:00 app[web.1]: ReferenceError: /app/views/index.ejs:22
2017-10-17T20:28:02.190131+00:00 app[web.1]:     20|             window.attachApp(
2017-10-17T20:28:02.190132+00:00 app[web.1]:     21|               context.psid,
2017-10-17T20:28:02.190133+00:00 app[web.1]:  >> 22|               <%= listId %>,
2017-10-17T20:28:02.190134+00:00 app[web.1]:     23|               "<%= socketAddress %>",
2017-10-17T20:28:02.190134+00:00 app[web.1]:     24|               context.thread_type);
2017-10-17T20:28:02.190135+00:00 app[web.1]:     25|           }, function error(err) {
2017-10-17T20:28:02.190136+00:00 app[web.1]:
2017-10-17T20:28:02.190142+00:00 app[web.1]: listId is not defined
2017-10-17T20:28:02.190144+00:00 app[web.1]:     at eval (eval at compile (/app/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:22:26)
`

**Comment by eoinclancy1** [comment]
![image](https://user-images.githubusercontent.com/22260484/31693952-4bf65366-b399-11e7-9700-fc5a32ddb1b1.png)
![image](https://user-images.githubusercontent.com/22260484/31693969-60059f1a-b399-11e7-892b-970549baa7f0.png)

**Comment by embee8** [comment]
When does this error occur? Are you trying to open the extension from within Messenger or from the browser? I fixed a similar error in the last commit. Can you redeploy and check the status? Going to close this issue but feel free to re-open it.
